# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5f0c921d991544599e45e70f0310de3cd6326144c85bc82c227ec505ab2adabccde5ce23b4764392b7a071bde32c1b7f0b0fa440a4f005cf81ac4bab6084d39

test:
  secret_key_base: e22f8f0467adc7991c153223b1b51755c3717526d8bc56b80ae0dd0702144a006af6374982e4440313c08e3c817bec126dd6a9311a1afdb751689e9c4e384ec2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
